<?php

namespace App\Console\Commands;

use App\Models\Language;
use App\Models\TranslationKey;
use App\Models\UiTranslation;
use App\Services\TranslationRegistryService;
use App\Services\TranslationService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class LocalizationSyncLanguagesCommand extends Command
{
    protected $signature = 'localization:sync-languages';
    protected $description = 'Synchronize all translation keys with active languages, ensuring missing translation rows are generated';

    public function handle(): int
    {
        $this->info('🔄 Starting synchronization of active languages for translation keys...');

        $activeLanguages = Language::active()->get();
        if ($activeLanguages->isEmpty()) {
            $this->error('No active languages found in the system.');
            return self::FAILURE;
        }

        $this->info('Languages to process: ' . $activeLanguages->pluck('code')->implode(', '));

        $insertedCount = 0;
        $registryService = app(TranslationRegistryService::class);

        DB::transaction(function () use ($activeLanguages, $registryService, &$insertedCount) {
            TranslationKey::chunk(100, function ($keys) use ($activeLanguages, $registryService, &$insertedCount) {
                $keyIds = $keys->pluck('id')->toArray();
                
                // Fetch existing relations for these keys to avoid duplicate insert checks
                $existing = UiTranslation::whereIn('translation_key_id', $keyIds)
                    ->select('translation_key_id', 'language_id')
                    ->get()
                    ->groupBy('translation_key_id')
                    ->map(function ($items) {
                        return $items->pluck('language_id')->toArray();
                    })
                    ->toArray();

                $inserts = [];

                foreach ($keys as $key) {
                    $existingLangIds = $existing[$key->id] ?? [];

                    foreach ($activeLanguages as $lang) {
                        if (!in_array($lang->id, $existingLangIds, true)) {
                            $value = null;
                            $isAutoGenerated = true;

                            if ($lang->code === 'en') {
                                $value = $registryService->generateDefaultEnglish($key->key);
                                $isAutoGenerated = false;
                            }

                            $inserts[] = [
                                'translation_key_id' => $key->id,
                                'language_id' => $lang->id,
                                'value' => $value,
                                'is_auto_generated' => $isAutoGenerated,
                                'created_at' => now(),
                                'updated_at' => now(),
                            ];
                        }
                    }
                }

                if (!empty($inserts)) {
                    UiTranslation::insert($inserts);
                    $insertedCount += count($inserts);
                }
            });
        });

        // Clear all translation caches to take immediate effect
        app(TranslationService::class)->clearCache();

        $this->info("✅ Sync complete. Generated {$insertedCount} missing UI translation rows.");

        return self::SUCCESS;
    }
}
