<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name_ar' => 'الفاتحة', 'name_ku' => 'الفاتحة', 'name_en' => 'Al-Fatihah', 'revelation_type' => 'makki', 'ayah_count' => 7],
            ['number' => 2, 'name_ar' => 'البقرة', 'name_ku' => 'البقرة', 'name_en' => 'Al-Baqarah', 'revelation_type' => 'madani', 'ayah_count' => 286],
            ['number' => 3, 'name_ar' => 'آل عمران', 'name_ku' => 'آل عمران', 'name_en' => 'Ali \'Imran', 'revelation_type' => 'madani', 'ayah_count' => 200],
            ['number' => 4, 'name_ar' => 'النساء', 'name_ku' => 'النساء', 'name_en' => 'An-Nisa', 'revelation_type' => 'madani', 'ayah_count' => 176],
            ['number' => 5, 'name_ar' => 'المائدة', 'name_ku' => 'المائدة', 'name_en' => 'Al-Ma\'idah', 'revelation_type' => 'madani', 'ayah_count' => 120],
            ['number' => 6, 'name_ar' => 'الأنعام', 'name_ku' => 'الأنعام', 'name_en' => 'Al-An\'am', 'revelation_type' => 'makki', 'ayah_count' => 165],
            ['number' => 7, 'name_ar' => 'الأعراف', 'name_ku' => 'الأعراف', 'name_en' => 'Al-A\'raf', 'revelation_type' => 'makki', 'ayah_count' => 206],
            ['number' => 8, 'name_ar' => 'الأنفال', 'name_ku' => 'الأنفال', 'name_en' => 'Al-Anfal', 'revelation_type' => 'madani', 'ayah_count' => 75],
            ['number' => 9, 'name_ar' => 'التوبة', 'name_ku' => 'التوبة', 'name_en' => 'At-Tawbah', 'revelation_type' => 'madani', 'ayah_count' => 129],
            ['number' => 10, 'name_ar' => 'يونس', 'name_ku' => 'يونس', 'name_en' => 'Yunus', 'revelation_type' => 'makki', 'ayah_count' => 109],
            ['number' => 11, 'name_ar' => 'هود', 'name_ku' => 'هود', 'name_en' => 'Hud', 'revelation_type' => 'makki', 'ayah_count' => 123],
            ['number' => 12, 'name_ar' => 'يوسف', 'name_ku' => 'يوسف', 'name_en' => 'Yusuf', 'revelation_type' => 'makki', 'ayah_count' => 111],
            ['number' => 13, 'name_ar' => 'الرعد', 'name_ku' => 'الرعد', 'name_en' => 'Ar-Ra\'d', 'revelation_type' => 'madani', 'ayah_count' => 43],
            ['number' => 14, 'name_ar' => 'ابراهيم', 'name_ku' => 'إبراهيم', 'name_en' => 'Ibrahim', 'revelation_type' => 'makki', 'ayah_count' => 52],
            ['number' => 15, 'name_ar' => 'الحجر', 'name_ku' => 'الحجر', 'name_en' => 'Al-Hijr', 'revelation_type' => 'makki', 'ayah_count' => 99],
            ['number' => 16, 'name_ar' => 'النحل', 'name_ku' => 'النحل', 'name_en' => 'An-Nahl', 'revelation_type' => 'makki', 'ayah_count' => 128],
            ['number' => 17, 'name_ar' => 'الإسراء', 'name_ku' => 'الإسراء', 'name_en' => 'Al-Isra', 'revelation_type' => 'makki', 'ayah_count' => 111],
            ['number' => 18, 'name_ar' => 'الكهف', 'name_ku' => 'الكهف', 'name_en' => 'Al-Kahf', 'revelation_type' => 'makki', 'ayah_count' => 110],
            ['number' => 19, 'name_ar' => 'مريم', 'name_ku' => 'مريم', 'name_en' => 'Maryam', 'revelation_type' => 'makki', 'ayah_count' => 98],
            ['number' => 20, 'name_ar' => 'طه', 'name_ku' => 'طه', 'name_en' => 'Ta-Ha', 'revelation_type' => 'makki', 'ayah_count' => 135],
            ['number' => 21, 'name_ar' => 'الأنبياء', 'name_ku' => 'الأنبياء', 'name_en' => 'Al-Anbiya', 'revelation_type' => 'makki', 'ayah_count' => 112],
            ['number' => 22, 'name_ar' => 'الحج', 'name_ku' => 'الحج', 'name_en' => 'Al-Hajj', 'revelation_type' => 'madani', 'ayah_count' => 78],
            ['number' => 23, 'name_ar' => 'المؤمنون', 'name_ku' => 'المؤمنون', 'name_en' => 'Al-Mu\'minun', 'revelation_type' => 'makki', 'ayah_count' => 118],
            ['number' => 24, 'name_ar' => 'النور', 'name_ku' => 'النور', 'name_en' => 'An-Nur', 'revelation_type' => 'madani', 'ayah_count' => 64],
            ['number' => 25, 'name_ar' => 'الفرقان', 'name_ku' => 'الفرقان', 'name_en' => 'Al-Furqan', 'revelation_type' => 'makki', 'ayah_count' => 77],
            ['number' => 26, 'name_ar' => 'الشعراء', 'name_ku' => 'الشعراء', 'name_en' => 'Ash-Shu\'ara', 'revelation_type' => 'makki', 'ayah_count' => 227],
            ['number' => 27, 'name_ar' => 'النمل', 'name_ku' => 'النمل', 'name_en' => 'An-Naml', 'revelation_type' => 'makki', 'ayah_count' => 93],
            ['number' => 28, 'name_ar' => 'القصص', 'name_ku' => 'القصص', 'name_en' => 'Al-Qasas', 'revelation_type' => 'makki', 'ayah_count' => 88],
            ['number' => 29, 'name_ar' => 'العنكبوت', 'name_ku' => 'العنكبوت', 'name_en' => 'Al-\'Ankabut', 'revelation_type' => 'makki', 'ayah_count' => 69],
            ['number' => 30, 'name_ar' => 'الروم', 'name_ku' => 'الروم', 'name_en' => 'Ar-Rum', 'revelation_type' => 'makki', 'ayah_count' => 60],
            ['number' => 31, 'name_ar' => 'لقمان', 'name_ku' => 'لقمان', 'name_en' => 'Luqman', 'revelation_type' => 'makki', 'ayah_count' => 34],
            ['number' => 32, 'name_ar' => 'السجدة', 'name_ku' => 'السجدة', 'name_en' => 'As-Sajdah', 'revelation_type' => 'makki', 'ayah_count' => 30],
            ['number' => 33, 'name_ar' => 'الأحزاب', 'name_ku' => 'الأحزاب', 'name_en' => 'Al-Ahzab', 'revelation_type' => 'madani', 'ayah_count' => 73],
            ['number' => 34, 'name_ar' => 'سبأ', 'name_ku' => 'سبأ', 'name_en' => 'Saba', 'revelation_type' => 'makki', 'ayah_count' => 54],
            ['number' => 35, 'name_ar' => 'فاطر', 'name_ku' => 'فاطر', 'name_en' => 'Fatir', 'revelation_type' => 'makki', 'ayah_count' => 45],
            ['number' => 36, 'name_ar' => 'يس', 'name_ku' => 'يس', 'name_en' => 'Ya-Sin', 'revelation_type' => 'makki', 'ayah_count' => 83],
            ['number' => 37, 'name_ar' => 'الصافات', 'name_ku' => 'الصافات', 'name_en' => 'As-Saffat', 'revelation_type' => 'makki', 'ayah_count' => 182],
            ['number' => 38, 'name_ar' => 'ص', 'name_ku' => 'ص', 'name_en' => 'Sad', 'revelation_type' => 'makki', 'ayah_count' => 88],
            ['number' => 39, 'name_ar' => 'الزمر', 'name_ku' => 'الزمر', 'name_en' => 'Az-Zumar', 'revelation_type' => 'makki', 'ayah_count' => 75],
            ['number' => 40, 'name_ar' => 'غافر', 'name_ku' => 'غافر', 'name_en' => 'Ghafir', 'revelation_type' => 'makki', 'ayah_count' => 85],
            ['number' => 41, 'name_ar' => 'فصلت', 'name_ku' => 'فصلت', 'name_en' => 'Fussilat', 'revelation_type' => 'makki', 'ayah_count' => 54],
            ['number' => 42, 'name_ar' => 'الشورى', 'name_ku' => 'الشورى', 'name_en' => 'Ash-Shuraa', 'revelation_type' => 'makki', 'ayah_count' => 53],
            ['number' => 43, 'name_ar' => 'الزخرف', 'name_ku' => 'الزخرف', 'name_en' => 'Az-Zukhruf', 'revelation_type' => 'makki', 'ayah_count' => 89],
            ['number' => 44, 'name_ar' => 'الدخان', 'name_ku' => 'الدخان', 'name_en' => 'Ad-Dukhan', 'revelation_type' => 'makki', 'ayah_count' => 59],
            ['number' => 45, 'name_ar' => 'الجاثية', 'name_ku' => 'الجاثية', 'name_en' => 'Al-Jathiyah', 'revelation_type' => 'makki', 'ayah_count' => 37],
            ['number' => 46, 'name_ar' => 'الأحقاف', 'name_ku' => 'الأحقاف', 'name_en' => 'Al-Ahqaf', 'revelation_type' => 'makki', 'ayah_count' => 35],
            ['number' => 47, 'name_ar' => 'محمد', 'name_ku' => 'محمد', 'name_en' => 'Muhammad', 'revelation_type' => 'madani', 'ayah_count' => 38],
            ['number' => 48, 'name_ar' => 'الفتح', 'name_ku' => 'الفتح', 'name_en' => 'Al-Fath', 'revelation_type' => 'madani', 'ayah_count' => 29],
            ['number' => 49, 'name_ar' => 'الحجرات', 'name_ku' => 'الحجرات', 'name_en' => 'Al-Hujurat', 'revelation_type' => 'madani', 'ayah_count' => 18],
            ['number' => 50, 'name_ar' => 'ق', 'name_ku' => 'ق', 'name_en' => 'Qaf', 'revelation_type' => 'makki', 'ayah_count' => 45],
            ['number' => 51, 'name_ar' => 'الذاريات', 'name_ku' => 'الذاريات', 'name_en' => 'Adh-Dhariyat', 'revelation_type' => 'makki', 'ayah_count' => 60],
            ['number' => 52, 'name_ar' => 'الطور', 'name_ku' => 'الطور', 'name_en' => 'At-Tur', 'revelation_type' => 'makki', 'ayah_count' => 49],
            ['number' => 53, 'name_ar' => 'النجم', 'name_ku' => 'النجم', 'name_en' => 'An-Najm', 'revelation_type' => 'makki', 'ayah_count' => 62],
            ['number' => 54, 'name_ar' => 'القمر', 'name_ku' => 'القمر', 'name_en' => 'Al-Qamar', 'revelation_type' => 'makki', 'ayah_count' => 55],
            ['number' => 55, 'name_ar' => 'الرحمن', 'name_ku' => 'الرحمن', 'name_en' => 'Ar-Rahman', 'revelation_type' => 'madani', 'ayah_count' => 78],
            ['number' => 56, 'name_ar' => 'الواقعة', 'name_ku' => 'الواقعة', 'name_en' => 'Al-Waqi\'ah', 'revelation_type' => 'makki', 'ayah_count' => 96],
            ['number' => 57, 'name_ar' => 'الحديد', 'name_ku' => 'الحديد', 'name_en' => 'Al-Hadid', 'revelation_type' => 'madani', 'ayah_count' => 29],
            ['number' => 58, 'name_ar' => 'المجادلة', 'name_ku' => 'المجادلة', 'name_en' => 'Al-Mujadila', 'revelation_type' => 'madani', 'ayah_count' => 22],
            ['number' => 59, 'name_ar' => 'الحشر', 'name_ku' => 'الحشر', 'name_en' => 'Al-Hashr', 'revelation_type' => 'madani', 'ayah_count' => 24],
            ['number' => 60, 'name_ar' => 'الممتحنة', 'name_ku' => 'الممتحنة', 'name_en' => 'Al-Mumtahanah', 'revelation_type' => 'madani', 'ayah_count' => 13],
            ['number' => 61, 'name_ar' => 'الصف', 'name_ku' => 'الصف', 'name_en' => 'As-Saff', 'revelation_type' => 'madani', 'ayah_count' => 14],
            ['number' => 62, 'name_ar' => 'الجمعة', 'name_ku' => 'الجمعة', 'name_en' => 'Al-Jumu\'ah', 'revelation_type' => 'madani', 'ayah_count' => 11],
            ['number' => 63, 'name_ar' => 'المنافقون', 'name_ku' => 'المنافقون', 'name_en' => 'Al-Munafiqun', 'revelation_type' => 'madani', 'ayah_count' => 11],
            ['number' => 64, 'name_ar' => 'التغابن', 'name_ku' => 'التغابن', 'name_en' => 'At-Taghabun', 'revelation_type' => 'madani', 'ayah_count' => 18],
            ['number' => 65, 'name_ar' => 'الطلاق', 'name_ku' => 'الطلاق', 'name_en' => 'At-Talaq', 'revelation_type' => 'madani', 'ayah_count' => 12],
            ['number' => 66, 'name_ar' => 'التحريم', 'name_ku' => 'التحريم', 'name_en' => 'At-Tahrim', 'revelation_type' => 'madani', 'ayah_count' => 12],
            ['number' => 67, 'name_ar' => 'الملك', 'name_ku' => 'الملك', 'name_en' => 'Al-Mulk', 'revelation_type' => 'makki', 'ayah_count' => 30],
            ['number' => 68, 'name_ar' => 'القلم', 'name_ku' => 'القلم', 'name_en' => 'Al-Qalam', 'revelation_type' => 'makki', 'ayah_count' => 52],
            ['number' => 69, 'name_ar' => 'الحاقة', 'name_ku' => 'الحاقة', 'name_en' => 'Al-Haqqah', 'revelation_type' => 'makki', 'ayah_count' => 52],
            ['number' => 70, 'name_ar' => 'المعارج', 'name_ku' => 'المعارج', 'name_en' => 'Al-Ma\'arij', 'revelation_type' => 'makki', 'ayah_count' => 44],
            ['number' => 71, 'name_ar' => 'نوح', 'name_ku' => 'نوح', 'name_en' => 'Nuh', 'revelation_type' => 'makki', 'ayah_count' => 28],
            ['number' => 72, 'name_ar' => 'الجن', 'name_ku' => 'الجن', 'name_en' => 'Al-Jinn', 'revelation_type' => 'makki', 'ayah_count' => 28],
            ['number' => 73, 'name_ar' => 'المزمل', 'name_ku' => 'المزمل', 'name_en' => 'Al-Muzzammil', 'revelation_type' => 'makki', 'ayah_count' => 20],
            ['number' => 74, 'name_ar' => 'المدثر', 'name_ku' => 'المدثر', 'name_en' => 'Al-Muddaththir', 'revelation_type' => 'makki', 'ayah_count' => 56],
            ['number' => 75, 'name_ar' => 'القيامة', 'name_ku' => 'القيامة', 'name_en' => 'Al-Qiyamah', 'revelation_type' => 'makki', 'ayah_count' => 40],
            ['number' => 76, 'name_ar' => 'الانسان', 'name_ku' => 'الإنسان', 'name_en' => 'Al-Insan', 'revelation_type' => 'madani', 'ayah_count' => 31],
            ['number' => 77, 'name_ar' => 'المرسلات', 'name_ku' => 'المرسلات', 'name_en' => 'Al-Mursalat', 'revelation_type' => 'makki', 'ayah_count' => 50],
            ['number' => 78, 'name_ar' => 'النبأ', 'name_ku' => 'النبأ', 'name_en' => 'An-Naba', 'revelation_type' => 'makki', 'ayah_count' => 40],
            ['number' => 79, 'name_ar' => 'النازعات', 'name_ku' => 'النازعات', 'name_en' => 'An-Nazi\'at', 'revelation_type' => 'makki', 'ayah_count' => 46],
            ['number' => 80, 'name_ar' => 'عبس', 'name_ku' => 'عبس', 'name_en' => '\'Abasa', 'revelation_type' => 'makki', 'ayah_count' => 42],
            ['number' => 81, 'name_ar' => 'التكوير', 'name_ku' => 'التكوير', 'name_en' => 'At-Takwir', 'revelation_type' => 'makki', 'ayah_count' => 29],
            ['number' => 82, 'name_ar' => 'الإنفطار', 'name_ku' => 'الإنفطار', 'name_en' => 'Al-Infitar', 'revelation_type' => 'makki', 'ayah_count' => 19],
            ['number' => 83, 'name_ar' => 'المطففين', 'name_ku' => 'المطففين', 'name_en' => 'Al-Mutaffifin', 'revelation_type' => 'makki', 'ayah_count' => 36],
            ['number' => 84, 'name_ar' => 'الإنشقاق', 'name_ku' => 'الإنشقاق', 'name_en' => 'Al-Inshiqaq', 'revelation_type' => 'makki', 'ayah_count' => 25],
            ['number' => 85, 'name_ar' => 'البروج', 'name_ku' => 'البروج', 'name_en' => 'Al-Buruj', 'revelation_type' => 'makki', 'ayah_count' => 22],
            ['number' => 86, 'name_ar' => 'الطارق', 'name_ku' => 'الطارق', 'name_en' => 'At-Tariq', 'revelation_type' => 'makki', 'ayah_count' => 17],
            ['number' => 87, 'name_ar' => 'الأعلى', 'name_ku' => 'الأعلى', 'name_en' => 'Al-A\'la', 'revelation_type' => 'makki', 'ayah_count' => 19],
            ['number' => 88, 'name_ar' => 'الغاشية', 'name_ku' => 'الغاشية', 'name_en' => 'Al-Ghashiyah', 'revelation_type' => 'makki', 'ayah_count' => 26],
            ['number' => 89, 'name_ar' => 'الفجر', 'name_ku' => 'الفجر', 'name_en' => 'Al-Fajr', 'revelation_type' => 'makki', 'ayah_count' => 30],
            ['number' => 90, 'name_ar' => 'البلد', 'name_ku' => 'البلد', 'name_en' => 'Al-Balad', 'revelation_type' => 'makki', 'ayah_count' => 20],
            ['number' => 91, 'name_ar' => 'الشمس', 'name_ku' => 'الشمس', 'name_en' => 'Ash-Shams', 'revelation_type' => 'makki', 'ayah_count' => 15],
            ['number' => 92, 'name_ar' => 'الليل', 'name_ku' => 'الليل', 'name_en' => 'Al-Layl', 'revelation_type' => 'makki', 'ayah_count' => 21],
            ['number' => 93, 'name_ar' => 'الضحى', 'name_ku' => 'الضحى', 'name_en' => 'Ad-Duhaa', 'revelation_type' => 'makki', 'ayah_count' => 11],
            ['number' => 94, 'name_ar' => 'الشرح', 'name_ku' => 'الشرح', 'name_en' => 'Ash-Sharh', 'revelation_type' => 'makki', 'ayah_count' => 8],
            ['number' => 95, 'name_ar' => 'التين', 'name_ku' => 'التين', 'name_en' => 'At-Tin', 'revelation_type' => 'makki', 'ayah_count' => 8],
            ['number' => 96, 'name_ar' => 'العلق', 'name_ku' => 'العلق', 'name_en' => 'Al-\'Alaq', 'revelation_type' => 'makki', 'ayah_count' => 19],
            ['number' => 97, 'name_ar' => 'القدر', 'name_ku' => 'القدر', 'name_en' => 'Al-Qadr', 'revelation_type' => 'makki', 'ayah_count' => 5],
            ['number' => 98, 'name_ar' => 'البينة', 'name_ku' => 'البينة', 'name_en' => 'Al-Bayyinah', 'revelation_type' => 'madani', 'ayah_count' => 8],
            ['number' => 99, 'name_ar' => 'الزلزلة', 'name_ku' => 'الزلزلة', 'name_en' => 'Az-Zalzalah', 'revelation_type' => 'madani', 'ayah_count' => 8],
            ['number' => 100, 'name_ar' => 'العاديات', 'name_ku' => 'العاديات', 'name_en' => 'Al-\'Adiyat', 'revelation_type' => 'makki', 'ayah_count' => 11],
            ['number' => 101, 'name_ar' => 'القارعة', 'name_ku' => 'القارعة', 'name_en' => 'Al-Qari\'ah', 'revelation_type' => 'makki', 'ayah_count' => 11],
            ['number' => 102, 'name_ar' => 'التكاثر', 'name_ku' => 'التكاثر', 'name_en' => 'At-Takathur', 'revelation_type' => 'makki', 'ayah_count' => 8],
            ['number' => 103, 'name_ar' => 'العصر', 'name_ku' => 'العصر', 'name_en' => 'Al-\'Asr', 'revelation_type' => 'makki', 'ayah_count' => 3],
            ['number' => 104, 'name_ar' => 'الهمزة', 'name_ku' => 'الهمزة', 'name_en' => 'Al-Humazah', 'revelation_type' => 'makki', 'ayah_count' => 9],
            ['number' => 105, 'name_ar' => 'الفيل', 'name_ku' => 'الفيل', 'name_en' => 'Al-Fil', 'revelation_type' => 'makki', 'ayah_count' => 5],
            ['number' => 106, 'name_ar' => 'قريش', 'name_ku' => 'قريش', 'name_en' => 'Quraysh', 'revelation_type' => 'makki', 'ayah_count' => 4],
            ['number' => 107, 'name_ar' => 'الماعون', 'name_ku' => 'الماعون', 'name_en' => 'Al-Ma\'un', 'revelation_type' => 'makki', 'ayah_count' => 7],
            ['number' => 108, 'name_ar' => 'الكوثر', 'name_ku' => 'الكوثر', 'name_en' => 'Al-Kawthar', 'revelation_type' => 'makki', 'ayah_count' => 3],
            ['number' => 109, 'name_ar' => 'الكافرون', 'name_ku' => 'الكافرون', 'name_en' => 'Al-Kafirun', 'revelation_type' => 'makki', 'ayah_count' => 6],
            ['number' => 110, 'name_ar' => 'النصر', 'name_ku' => 'النصر', 'name_en' => 'An-Nasr', 'revelation_type' => 'madani', 'ayah_count' => 3],
            ['number' => 111, 'name_ar' => 'المسد', 'name_ku' => 'المسد', 'name_en' => 'Al-Masad', 'revelation_type' => 'makki', 'ayah_count' => 5],
            ['number' => 112, 'name_ar' => 'الإخلاص', 'name_ku' => 'الإخلاص', 'name_en' => 'Al-Ikhlas', 'revelation_type' => 'makki', 'ayah_count' => 4],
            ['number' => 113, 'name_ar' => 'الفلق', 'name_ku' => 'الفلق', 'name_en' => 'Al-Falaq', 'revelation_type' => 'makki', 'ayah_count' => 5],
            ['number' => 114, 'name_ar' => 'الناس', 'name_ku' => 'الناس', 'name_en' => 'An-Nas', 'revelation_type' => 'makki', 'ayah_count' => 6],
        ];

        foreach ($surahs as $surah) {
            Surah::updateOrCreate(
                ['number' => $surah['number']],
                array_merge($surah, ['is_active' => true])
            );
        }
    }
}
