<?php

namespace App\Services;

use App\Models\UiTranslation;
use App\Models\UiTranslationVersion;
use Illuminate\Support\Facades\DB;

class AiTranslationAnalyticsService
{
    /**
     * Get AI translation efficiency statistics.
     */
    public function getAiAnalytics(): array
    {
        // 1. Total translations generated by AI
        $aiTranslations = UiTranslation::where('is_auto_generated', true)->get();
        
        $aiGeneratedIds = DB::table('ui_translation_versions')
            ->where('change_source', 'ai')
            ->pluck('ui_translation_id')
            ->unique()
            ->toArray();

        $allAiIds = array_unique(array_merge($aiTranslations->pluck('id')->toArray(), $aiGeneratedIds));
        $totalAi = count($allAiIds);

        if ($totalAi === 0) {
            return [
                'ai_generated' => 0,
                'edited_after_ai' => 0,
                'accepted_as_is' => 0,
                'acceptance_rate' => 100.0,
            ];
        }

        // 2. Identify translations updated manually after AI generation
        $editedAfterAiCount = 0;

        $versionsGrouped = DB::table('ui_translation_versions')
            ->whereIn('ui_translation_id', $allAiIds)
            ->orderBy('id', 'asc')
            ->get()
            ->groupBy('ui_translation_id');

        foreach ($versionsGrouped as $tId => $versions) {
            $hasAi = false;
            $hasManualAfterAi = false;

            foreach ($versions as $v) {
                if ($v->change_source === 'ai') {
                    $hasAi = true;
                } elseif ($hasAi && ($v->change_source === 'manual' || $v->change_source === 'rollback')) {
                    $hasManualAfterAi = true;
                    break;
                }
            }

            if ($hasManualAfterAi) {
                $editedAfterAiCount++;
            }
        }

        $acceptedAsIs = $totalAi - $editedAfterAiCount;
        $acceptanceRate = round(($acceptedAsIs / $totalAi) * 100, 2);

        return [
            'ai_generated' => $totalAi,
            'edited_after_ai' => $editedAfterAiCount,
            'accepted_as_is' => $acceptedAsIs,
            'acceptance_rate' => $acceptanceRate,
        ];
    }
}
