<?php

namespace App\Services;

use App\Models\Language;
use App\Models\TranslationKey;
use App\Models\UiTranslation;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class TranslationService
{
    /**
     * Memory cache to prevent duplicate auto-generations within the same request.
     */
    protected static array $autoGeneratedInRequest = [];

    /**
     * Get a UI translation for the given key.
     */
    public function get(string $key, array $replace = [], ?string $locale = null): string
    {
        $startTime = microtime(true);
        $locale ??= app()->getLocale();

        $cacheHit = false;
        $dbFallback = false;
        $aiFallback = false;
        $isMissing = false;

        // 1. Try loading translations for current locale
        $translations = $this->getTranslationsForLocale($locale);

        if (isset($translations[$key]) && $translations[$key] !== '') {
            $cacheHit = true;
            $result = $this->replacePlaceholders($translations[$key], $replace);
        } else {
            // 2. Fallback to default language
            $defaultLang = Language::where('is_default', true)->first();
            if ($defaultLang && $defaultLang->code !== $locale) {
                $defaultTranslations = $this->getTranslationsForLocale($defaultLang->code);
                if (isset($defaultTranslations[$key]) && $defaultTranslations[$key] !== '') {
                    $dbFallback = true;
                    $result = $this->replacePlaceholders($defaultTranslations[$key], $replace);
                }
            }
        }

        if (!isset($result)) {
            $isMissing = true;
            // 3. Key is missing — trigger auto-generation
            $this->autoGenerateMissingKey($key);

            // Debug mode prefix for missing keys in local environment
            if (app()->environment('local')) {
                $result = $this->replacePlaceholders("⚠{$key}", $replace);
            } else {
                $result = $this->replacePlaceholders($key, $replace);
            }
        }

        $elapsedTimeMs = (microtime(true) - $startTime) * 1000;

        try {
            app(TranslationAnalyticsService::class)->logHit($key, $locale, $isMissing);
            app(TranslationPerformanceService::class)->logPerformance($elapsedTimeMs, $cacheHit, $dbFallback, $aiFallback);
        } catch (\Exception $e) {
            // Ignore analytics tracking failures to keep request alive
        }

        return $result;
    }

    /**
     * Automatically insert missing keys and generate empty records.
     */
    public function autoGenerateMissingKey(string $key): void
    {
        // Check configuration first
        if (!config('translations.auto_generate', true)) {
            return;
        }

        // Prevent duplicate generation in the same request thread
        if (in_array($key, self::$autoGeneratedInRequest, true)) {
            return;
        }

        self::$autoGeneratedInRequest[] = $key;

        try {
            DB::transaction(function () use ($key) {
                $parts = explode('.', $key);
                $group = count($parts) > 1 ? $parts[0] : 'general';

                $translationKey = TranslationKey::firstOrCreate(
                    ['key' => $key],
                    [
                        'group' => $group,
                        'description' => 'Auto-generated missing key',
                    ]
                );

                $languages = Language::all();
                foreach ($languages as $language) {
                    UiTranslation::firstOrCreate(
                        [
                            'translation_key_id' => $translationKey->id,
                            'language_id' => $language->id,
                        ],
                        [
                            'value' => null,
                            'is_auto_generated' => true,
                        ]
                    );
                }
            });

            // Clear cache to make the key available for fallback / editing immediately
            $this->clearCache();
        } catch (\Exception $e) {
            Log::error("Failed to auto-generate translation key '{$key}': " . $e->getMessage());
        }
    }

    /**
     * Invalidate caches.
     */
    public function clearCache(?string $locale = null): void
    {
        if ($locale) {
            Cache::forget("translations_{$locale}");
        } else {
            // Flush all possible translation caches
            try {
                $locales = Language::pluck('code')->toArray();
            } catch (\Exception $e) {
                $locales = ['en', 'ku', 'ar'];
            }

            foreach ($locales as $code) {
                Cache::forget("translations_{$code}");
            }
        }

        // Apply tags flush if cache store is taggable (e.g. redis, memcached)
        if (Cache::getStore() instanceof \Illuminate\Cache\TaggableStore) {
            Cache::tags(['translations', 'languages'])->flush();
        }
    }

    /**
     * Get translations for a specific locale, utilizing cache.
     */
    public function getTranslationsForLocale(string $locale): array
    {
        $cacheKey = "translations_{$locale}";
        $fetcher = fn() => $this->loadTranslations($locale);

        if (Cache::getStore() instanceof \Illuminate\Cache\TaggableStore) {
            return Cache::tags(['translations', 'languages'])->remember($cacheKey, 3600, $fetcher);
        }

        return Cache::remember($cacheKey, 3600, $fetcher);
    }

    /**
     * Load translations directly from the database for a locale.
     */
    protected function loadTranslations(string $locale): array
    {
        try {
            $language = Language::where('code', $locale)->first();
            if (!$language) {
                return [];
            }

            return DB::table('translation_keys')
                ->join('ui_translations', 'ui_translations.translation_key_id', '=', 'translation_keys.id')
                ->where('ui_translations.language_id', $language->id)
                ->whereNotNull('ui_translations.value')
                ->where('ui_translations.value', '!=', '')
                ->pluck('ui_translations.value', 'translation_keys.key')
                ->toArray();
        } catch (\Exception $e) {
            Log::error("Failed to load UI translations for locale '{$locale}': " . $e->getMessage());
            return [];
        }
    }

    /**
     * Helper to replace placeholders like :key or {{key}} or {{ key }} in translations.
     */
    protected function replacePlaceholders(string $string, array $replace): string
    {
        if (empty($replace)) {
            return $string;
        }

        foreach ($replace as $key => $value) {
            $value = (string) $value;
            $string = str_replace(
                [":{$key}", "{{{$key}}}", "{{ {$key} }}"],
                $value,
                $string
            );
        }

        return $string;
    }
}
