<?php

namespace App\Services;

use App\Models\Language;
use App\Models\TranslationKey;
use App\Models\UiTranslation;
use App\Models\DynamicTranslationWarning;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Cache;

class TranslationRegistryService
{
    /**
     * Statically cached list of registered keys to prevent redundant DB check queries.
     */
    protected static ?array $registeredKeys = null;

    /**
     * Clear the static registered keys cache.
     */
    public static function clearStaticCache(): void
    {
        self::$registeredKeys = null;
    }

    /**
     * Check if a translation key is already registered in the database.
     */
    public function isKeyRegistered(string $key): bool
    {
        if (self::$registeredKeys === null) {
            try {
                self::$registeredKeys = TranslationKey::pluck('key')->toArray();
            } catch (\Exception $e) {
                return false;
            }
        }

        return in_array($key, self::$registeredKeys, true);
    }

    /**
     * Register a translation key in the registry database.
     * Generates groups and creates missing values for all active languages.
     */
    public function registerKey(string $key): TranslationKey
    {
        $parts = explode('.', $key);
        $group = count($parts) > 1 ? $parts[0] : 'general';

        if (self::$registeredKeys !== null && !in_array($key, self::$registeredKeys, true)) {
            self::$registeredKeys[] = $key;
        }

        return DB::transaction(function () use ($key, $group) {
            $translationKey = TranslationKey::firstOrCreate(
                ['key' => $key],
                [
                    'group' => $group,
                    'description' => 'Auto-discovered key',
                ]
            );

            // Get all active languages configured in the DB
            $languages = Language::all();
            
            foreach ($languages as $language) {
                // If it is English, we auto-generate default English value
                $value = null;
                $isAutoGenerated = true;

                if ($language->code === 'en') {
                    $value = $this->generateDefaultEnglish($key);
                    $isAutoGenerated = false;
                }

                UiTranslation::firstOrCreate(
                    [
                        'translation_key_id' => $translationKey->id,
                        'language_id' => $language->id,
                    ],
                    [
                        'value' => $value,
                        'is_auto_generated' => $isAutoGenerated,
                    ]
                );
            }

            return $translationKey;
        });
    }

    /**
     * Generate default English value from a key, stripping language suffixes.
     */
    public function generateDefaultEnglish(string $key): string
    {
        // Strip language suffixes (e.g. _ar, _en) from segments prior to formatting
        $key = preg_replace('/(?:_(?:ar|ku|en|tr|fa|fr|de|es|ru|ur))+(?=\.|$)/i', '', $key);

        $segments = explode('.', $key);
        $structuralWords = ['fields', 'actions', 'buttons', 'labels', 'hints', 'messages', 'errors', 'placeholders', 'placeholder', 'attributes', 'titles', 'titles_plural'];
        
        $useLastSegmentOnly = false;
        if (count($segments) >= 3) {
            foreach ($segments as $index => $seg) {
                if ($index < count($segments) - 1 && in_array($seg, $structuralWords)) {
                    $useLastSegmentOnly = true;
                    break;
                }
            }
        }
        
        $text = $useLastSegmentOnly ? end($segments) : implode(' ', $segments);
        $text = str_replace(['_', '-'], ' ', $text);
        
        // Title Case: e.g. "dashboard title" -> "Dashboard Title"
        return ucwords($text);
    }

    /**
     * Scan the entire codebase for translation keys.
     */
    public function scanCodebase(): array
    {
        $directories = [
            resource_path('views'),
            app_path('Http/Controllers'),
            app_path('View/Components'),
            app_path('Livewire'),
            app_path('Services'),
            app_path('Helpers'),
            app_path('Http/Middleware'),
            app_path('Notifications'),
            app_path('Mail'),
            app_path('Http/Resources'),
            base_path('routes'),
            base_path('config'),
        ];

        // Clear dynamic translation warnings from the DB
        try {
            if (\Illuminate\Support\Facades\Schema::hasTable('dynamic_translation_warnings')) {
                DynamicTranslationWarning::truncate();
            }
        } catch (\Exception $e) {
            // Ignore DB errors if migration hasn't run yet
        }

        $keys = [];
        $warnings = [];

        // Track stats for Task 4
        $totalFiles = 0;
        $bladeFiles = 0;
        $phpFiles = 0;

        foreach ($directories as $dir) {
            if (!file_exists($dir)) {
                continue;
            }

            try {
                $files = new \RecursiveIteratorIterator(
                    new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
                );

                foreach ($files as $file) {
                    if ($file->isDir()) {
                        continue;
                    }
                    
                    $filename = $file->getFilename();
                    $ext = $file->getExtension();
                    
                    if ($ext !== 'php' && !str_ends_with($filename, '.blade.php')) {
                        continue;
                    }

                    $totalFiles++;
                    if (str_ends_with($filename, '.blade.php')) {
                        $bladeFiles++;
                    } else {
                        $phpFiles++;
                    }

                    $content = file_get_contents($file->getPathname());
                    
                    // Run our file scanner
                    $result = $this->scanFile($file->getRealPath() ?: $file->getPathname(), $content);
                    
                    if (!empty($result['keys'])) {
                        $keys = array_merge($keys, $result['keys']);
                    }
                    if (!empty($result['warnings'])) {
                        $warnings = array_merge($warnings, $result['warnings']);
                    }
                }
            } catch (\Exception $e) {
                continue;
            }
        }

        // Save warnings to the database
        if (!empty($warnings)) {
            try {
                $chunks = array_chunk($warnings, 200);
                foreach ($chunks as $chunk) {
                    $insertData = [];
                    foreach ($chunk as $warn) {
                        $insertData[] = [
                            'file_path' => $warn['file_path'],
                            'line_number' => $warn['line_number'],
                            'expression' => $warn['expression'],
                            'created_at' => now(),
                        ];
                    }
                    DynamicTranslationWarning::insert($insertData);
                }
            } catch (\Exception $e) {
                // Ignore DB errors
            }
        }

        $uniqueKeys = array_unique($keys);
        
        // Save scan metadata in Cache
        Cache::put('translation_scan_stats', [
            'total_files' => $totalFiles,
            'blade_files' => $bladeFiles,
            'php_files' => $phpFiles,
            'keys_found' => count($uniqueKeys),
            'keys_raw' => count($keys),
            'dynamic_warnings' => count($warnings),
        ], 3600);

        return $uniqueKeys;
    }

    /**
     * Scan a single file content and extract translation keys and dynamic warning records.
     */
    public function scanFile(string $filePath, string $content): array
    {
        $discoveredKeys = [];
        $warnings = [];

        // Pattern matches: __, @lang, trans, Lang::get, Lang::has, translate, t helpers
        $pattern = '/\b(__|\@lang|trans|Lang::get|Lang::has|translate|\bt)\s*\(/';

        if (preg_match_all($pattern, $content, $matches, PREG_OFFSET_CAPTURE)) {
            foreach ($matches[0] as $match) {
                $funcName = $match[0];
                $startOffset = $match[1] + strlen($funcName); // offset of opening '('

                // Find matching closing parenthesis
                $len = strlen($content);
                $openCount = 1;
                $i = $startOffset;
                $argsBlock = '';

                while ($i < $len && $openCount > 0) {
                    $char = $content[$i];
                    if ($char === '(') {
                        $openCount++;
                    } elseif ($char === ')') {
                        $openCount--;
                    }
                    if ($openCount > 0) {
                        $argsBlock .= $char;
                    }
                    $i++;
                }

                if ($openCount === 0) {
                    $argsBlock = trim($argsBlock);
                    $lineNumber = substr_count(substr($content, 0, $match[1]), "\n") + 1;

                    $firstArg = $this->extractFirstArgument($argsBlock, $isDynamic, $expression);

                    if ($isDynamic) {
                        $warnings[] = [
                            'file_path' => $filePath,
                            'line_number' => $lineNumber,
                            'expression' => trim(rtrim($funcName, " (") . '(' . $argsBlock . ')'),
                        ];
                    } elseif ($firstArg !== null) {
                        $keyStr = trim($firstArg);
                        if (preg_match('/^[a-zA-Z0-9_\-\.\:\/\s\?,!@#\$%\^&\*\(\)\+=\{\}\[\]\\|;:\'"<>]+$/', $keyStr)) {
                            $discoveredKeys[] = $keyStr;
                        }
                    }
                }
            }
        }

        return [
            'keys' => $discoveredKeys,
            'warnings' => $warnings,
        ];
    }

    /**
     * Parse the arguments block to extract the first argument if it is a literal string.
     */
    protected function extractFirstArgument(string $argsBlock, &$isDynamic, &$expression): ?string
    {
        $isDynamic = false;
        $expression = $argsBlock;

        if ($argsBlock === '') {
            $isDynamic = true;
            return null;
        }

        $firstChar = $argsBlock[0];

        if ($firstChar === '$') {
            $isDynamic = true;
            return null;
        }

        if ($firstChar === "'" || $firstChar === '"') {
            $quote = $firstChar;
            $len = strlen($argsBlock);
            $i = 1;
            $escaped = false;
            $extracted = '';

            while ($i < $len) {
                $char = $argsBlock[$i];
                if ($escaped) {
                    $extracted .= $char;
                    $escaped = false;
                } elseif ($char === '\\') {
                    $escaped = true;
                } elseif ($char === $quote) {
                    break;
                } else {
                    $extracted .= $char;
                }
                $i++;
            }

            if ($quote === '"' && str_contains($extracted, '$')) {
                $isDynamic = true;
                return null;
            }

            $rest = trim(substr($argsBlock, $i + 1));
            
            if ($rest !== '' && $rest[0] === '.') {
                $isDynamic = true;
                return null;
            }

            return $extracted;
        }

        if (is_numeric($argsBlock)) {
            return $argsBlock;
        }

        $isDynamic = true;
        return null;
    }
}
